version: '3.2'

services:
  db:
    image: postgres:13
    container_name: dimatech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


volumes:
  postgres_data:
